/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductRouteImport } from './routes/product'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedConsultationIdRouteImport } from './routes/_authenticated/consultation.$id'

const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPatientsRoute,
} as any)
const AuthenticatedConsultationIdRoute =
  AuthenticatedConsultationIdRouteImport.update({
    id: '/consultation/$id',
    path: '/consultation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/product': typeof ProductRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/product': typeof ProductRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/product': typeof ProductRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/product'
    | '/appointments'
    | '/chat'
    | '/dashboard'
    | '/departments'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/settings'
    | '/staff'
    | '/consultation/$id'
    | '/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/product'
    | '/appointments'
    | '/chat'
    | '/dashboard'
    | '/departments'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/settings'
    | '/staff'
    | '/consultation/$id'
    | '/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/product'
    | '/_authenticated/appointments'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/patients'
    | '/_authenticated/pharmacy'
    | '/_authenticated/queue'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/consultation/$id'
    | '/_authenticated/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductRoute: typeof ProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/consultation/$id': {
      id: '/_authenticated/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof AuthenticatedConsultationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedConsultationIdRoute: typeof AuthenticatedConsultationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedConsultationIdRoute: AuthenticatedConsultationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProductRoute: ProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
